In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [4]:
df=pd.read_csv("/content/drive/MyDrive/btk-makine öğrenimi/çalışmalar/bilkav.com_odev_tenis.csv")


In [5]:
df

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [6]:
outlook=df.iloc[:,:1].values

In [7]:
outlook

array([['sunny'],
       ['sunny'],
       ['overcast'],
       ['rainy'],
       ['rainy'],
       ['rainy'],
       ['overcast'],
       ['sunny'],
       ['sunny'],
       ['rainy'],
       ['sunny'],
       ['overcast'],
       ['overcast'],
       ['rainy']], dtype=object)

In [29]:
ohe=preprocessing.OneHotEncoder()
outlook=ohe.fit_transform(outlook).toarray()

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]]


In [31]:
windy=df.iloc[:,3:4].values
windy

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [10]:
le=preprocessing.LabelEncoder()
windy=le.fit_transform(df.iloc[:,3:4])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
windy

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [12]:
play=df.iloc[:,4:5].values
play

array([['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no']], dtype=object)

In [13]:
le=preprocessing.LabelEncoder()
play=le.fit_transform(df.iloc[:,4:5])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
play

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [15]:
temp=df.iloc[:,1:3]
temp

temperature  humidity
0            85        85
1            80        90
2            83        86
3            70        96
4            68        80
5            65        70
6            64        65
7            72        95
8            69        70
9            75        80
10           75        70
11           72        90
12           81        75
13           71        91

In [16]:
sonuc1=pd.DataFrame(data=outlook,index=range(14),columns=["overcast","rainy","sunny"])
sonuc1

overcast  rainy  sunny
0        0.0    0.0    1.0
1        0.0    0.0    1.0
2        1.0    0.0    0.0
3        0.0    1.0    0.0
4        0.0    1.0    0.0
5        0.0    1.0    0.0
6        1.0    0.0    0.0
7        0.0    0.0    1.0
8        0.0    0.0    1.0
9        0.0    1.0    0.0
10       0.0    0.0    1.0
11       1.0    0.0    0.0
12       1.0    0.0    0.0
13       0.0    1.0    0.0

In [17]:
sonuc2=pd.DataFrame(data=windy,index=range(14),columns=["windy"])
sonuc2

windy
0       0
1       1
2       0
3       0
4       0
5       1
6       1
7       0
8       0
9       0
10      1
11      1
12      0
13      1

In [18]:
sonuc3=pd.DataFrame(data=play,index=range(14),columns=["play"])
sonuc3

play
0      0
1      0
2      1
3      1
4      1
5      0
6      1
7      0
8      1
9      1
10     1
11     1
12     1
13     0

In [19]:
s1=pd.concat([sonuc1,sonuc2],axis=1)
s2=pd.concat([s1,sonuc3],axis=1)
s3=pd.concat([s2,temp],axis=1)

In [20]:
s3

overcast  rainy  sunny  windy  play  temperature  humidity
0        0.0    0.0    1.0      0     0           85        85
1        0.0    0.0    1.0      1     0           80        90
2        1.0    0.0    0.0      0     1           83        86
3        0.0    1.0    0.0      0     1           70        96
4        0.0    1.0    0.0      0     1           68        80
5        0.0    1.0    0.0      1     0           65        70
6        1.0    0.0    0.0      1     1           64        65
7        0.0    0.0    1.0      0     0           72        95
8        0.0    0.0    1.0      0     1           69        70
9        0.0    1.0    0.0      0     1           75        80
10       0.0    0.0    1.0      1     1           75        70
11       1.0    0.0    0.0      1     1           72        90
12       1.0    0.0    0.0      0     1           81        75
13       0.0    1.0    0.0      1     0           71        91

In [24]:
#this is just an example for applying label encoder quicly
#from sklearn import preprocessing
#data2=df.apply(preprocessing.LabelEncoder().fit_transform)
#data2

In [33]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(s3.iloc[:,:-1],s3.iloc[:,-1:],test_size=0.33, random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression

regression=LinearRegression()
regression.fit(x_train,y_train)
y_pred=regression.predict(x_test)

In [39]:
y_pred,y_test

(array([[84.45365573],
        [63.93839954],
        [85.76050662],
        [64.21013241],
        [75.06793322]]),
     humidity
 8         70
 6         65
 4         80
 11        90
 2         86)

bacward elimination

In [40]:
import statsmodels.api as sm

In [42]:
X=np.append(arr=np.ones((14,1)).astype(int),values=s3.iloc[:,:-1],axis=1)
X

array([[ 1.,  0.,  0.,  1.,  0.,  0., 85.],
       [ 1.,  0.,  0.,  1.,  1.,  0., 80.],
       [ 1.,  1.,  0.,  0.,  0.,  1., 83.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 70.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 68.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 65.],
       [ 1.,  1.,  0.,  0.,  1.,  1., 64.],
       [ 1.,  0.,  0.,  1.,  0.,  0., 72.],
       [ 1.,  0.,  0.,  1.,  0.,  1., 69.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 75.],
       [ 1.,  0.,  0.,  1.,  1.,  1., 75.],
       [ 1.,  1.,  0.,  0.,  1.,  1., 72.],
       [ 1.,  1.,  0.,  0.,  0.,  1., 81.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 71.]])

In [45]:
X_l=s3.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(s3.iloc[:,-1:],X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Sun, 23 Jul 2023   Prob (F-statistic):              0.661
Time:                        19:40:10   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            52.3891     50.214      1.043      0.3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [46]:
X_l=s3.iloc[:,[0,1,2,4,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(s3.iloc[:,-1:],X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Sun, 23 Jul 2023   Prob (F-statistic):              0.546
Time:                        19:44:02   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            36.6564     39.905      0.919      0.3

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [53]:
first=x_train.iloc[:,0:3]
second=x_train.iloc[:,4:]
last_train=pd.concat([first,second],axis=1)

first=x_test.iloc[:,0:3]
second=x_test.iloc[:,4:]
last_test=pd.concat([first,second],axis=1)

In [59]:
regression.fit(last_train,y_train)
y_pred=regression.predict(last_test)
y_pred,y_test,

(array([[77.98135142],
        [68.29304916],
        [81.05037539],
        [71.44926132],
        [75.78905304]]),
     humidity
 8         70
 6         65
 4         80
 11        90
 2         86)